[versions]
android-gradle-plugin = "8.4.1"
androidx-wear-watchface = "1.2.1"

org-jetbrains-kotlin = "1.9.24"
org-jetbrains-kotlinx = "1.8.1"

[libraries]
androidx-core-ktx = "androidx.core:core-ktx:1.13.1"
androidx-datastore-preferences = "androidx.datastore:datastore-preferences:1.1.1"
androidx-wear-watchface-complications-data-source-ktx = { module = "androidx.wear.watchface:watchface-complications-data-source-ktx", version.ref = "androidx-wear-watchface" }
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "org-jetbrains-kotlin" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "org-jetbrains-kotlinx" }

[plugins]
com-android-application = { id = "com.android.application", version.ref = "android-gradle-plugin" }
com-diffplug-spotless = "com.diffplug.spotless:6.25.0"
